### ISSUE TITLE
Todo Items

### ISSUE THREAD

**Issue by mounikabodapati** [wuharvey/music-mike#59]
- [ ] Functions - Codegen
- [x] Functions - Type Inference
- [ ] Music Operators
- [x] Link up Synth in Code Gen
- [X]Makefile 
- [ ] Test List Concat and Chord List
- [ ] Map function
- [ ] Scanner -> music operators to different symbols
- [ ] Rhythm operator
- [ ] Paper
- [ ] Presentation
- [x] Test Cases that fail
- [ ] Clean up code
